version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    image: git.ailaplacelab.com/seba22/backend:dev
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/usr/src/app/.env
    environment:
      - NODE_ENV=development


volumes:
  mongodb_data:
  node_modules: 